config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "entries#calendar"

  resources :accounts do
    get :search, on: :collection
  end

  resources :charge_types, path: "charge-types" do
    get :search, on: :collection
  end

  resources :entries do
    member do
      post :mark_charged
      get :copy
      post :move
    end
    collection do
      get :calendar
      get :overview
      post :earning_spending_graph
      get :statistics
      post :statistics_graph, path: "statistics"
      get :autocomplete
      get :averages
      get :current_balance, path: "current-balance"
    end
  end

  resources :templates do
    collection do
      post :add_item
      post :launch_template
    end
  end

  devise_for :users,
             controllers: {
               passwords: "passwords",
               registrations: "registrations",
               sessions: "sessions",
               unlocks: "unlocks"
             },
             path_names: { sign_up: "join", sign_in: "login" },
             path: ""

  get "/about" => "application#about", as: :about
  get "/month" => "entries#calendar", as: :calendar

  scope module: :application do
    get :version
  end

  scope module: :internal do
    get :backup
    get :backup_failed, path: "backup/failed"
    get :backup_succeeded, path: "backup/succeeded"
    get :generate_backup, to: redirect("backup")
    post :generate_backup
  end
end

app/controllers/internal_controller.rb
# frozen_string_literal: true

# Tasks for logged in user.
class InternalController < ApplicationController
  before_action :authenticate_user!
  before_action :skip_backup_for_test, only: :generate_backup

  # # GET /backup
  # def backup
  # end

  # POST /generate_backup
  def generate_backup
    if Export.launch_export!
      current_user.update(
        last_backup_at: Time.zone.now,
        last_backup_entry_id: current_user.last_entry_id
      )
      redirect_to backup_succeeded_path
    else
      redirect_to backup_failed_path
    end
  end

  private

  def skip_backup_for_test
    redirect_to backup_succeeded_path if Rails.env.test?
  end
end

app/views/internal/_sidebar.html.haml
.col-12.col-md-3.col-xl-2.sidebar-wrapper{ style: "background-color: transparent;" }
  .sidebar
    #sidebar-nav-wrapper.sidebar-nav-wrapper.collapse{ style: "background-color: transparent;" }
      .pt-3.mx-3.my-0.ml-md-3.mb-md-3.mr-md-0
        %ul.sidebar-menu.sidebar-menu-shadow
          %li.sidebar-menu-header Dashboard
          %li= link_to "Dashboard", root_path, class: current_page?(root_path) ? "active" : nil

app/views/internal/_sidebar_setup.html.haml
.col-12.col-md-3.col-xl-2.sidebar-wrapper
  .sidebar
    #sidebar-nav-wrapper.sidebar-nav-wrapper.collapse
      .pt-3.py-md-3.mx-3.my-0.ml-md-3.mb-md-3.mr-md-0
        %ul.sidebar-menu.sidebar-menu-shadow
          %li.sidebar-menu-header= render "sidebar/toggle", title: "Setup"
          %li= link_to "Accounts", accounts_path, class: params[:controller] == "accounts" ? "active" : nil
          %li= link_to "Charge types", charge_types_path, class: params[:controller] == "charge_types" ? "active" : nil
          %li= link_to "Templates", templates_path, class: params[:controller] == "templates" ? "active" : nil

app/views/internal/_tabs.html.haml
- content_for :tabs do
  - current_page = params[:controller].in?(%w(internal))
  = link_to root_path, class: "link-unstyled d-inline-block px-3 pt-2 pb-2 rounded-top header-tab #{"border border-bottom-0 header-tab-active" if current_page}", data: { object: "#{"suppress-click" if current_page?(root_path)}" } do
    = icon("fas", "home")
    - if current_page
      Dashboard
    - else
      .d-none.d-sm-inline Dashboard
  - current_page = params[:controller].in?(%w(accounts charge_types templates))
  = link_to accounts_path, class: "link-unstyled d-inline-block px-3 pt-2 pb-2 rounded-top header-tab #{"border border-bottom-0 header-tab-active" if current_page}", data: { object: "#{"suppress-click" if current_page?(accounts_path)}" } do
    = icon("fas", "cog")
    - if current_page
      Settings
    - else
      .d-none.d-sm-inline Settings

app/views/internal/backup.html.haml
- @title = "Backup"

- content_for :header, @title

.text-center
  = link_to "Generate a New Data Backup", generate_backup_path, method: :post, class: "btn btn-lg btn-primary"

app/views/internal/backup_failed.html.haml
- @title = "Backup Failed"

- content_for :header, @title

.jumbotron.jumbotron-custom-text
  = icon("fas", "times-circle", class: "text-danger")
  Your data backup
  = succeed "." do
    %strong failed

app/views/internal/backup_succeeded.html.haml
- @title = "Backup Succeeded"

- content_for :header, @title

.jumbotron.jumbotron-custom-text
  = icon("fas", "check-circle", class: "text-success")
  Your data backup
  = succeed "." do
    %strong succeeded