config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "entries#calendar"

  resources :accounts do
    get :search, on: :collection
  end

  resources :charge_types, path: "charge-types" do
    get :search, on: :collection
  end

  resources :entries do
    member do
      post :mark_charged
      get :copy
      post :move
    end
    collection do
      get :calendar
      get :overview
      post :earning_spending_graph
      get :statistics
      post :statistics_graph, path: "statistics"
      get :autocomplete
      get :averages
      get :current_balance, path: "current-balance"
    end
  end

  resources :templates do
    collection do
      post :add_item
      post :launch_template
    end
  end

  devise_for :users,
             controllers: {
               passwords: "passwords",
               registrations: "registrations",
               sessions: "sessions",
               unlocks: "unlocks"
             },
             path_names: { sign_up: "join", sign_in: "login" },
             path: ""

  get "/about" => "application#about", as: :about
  get "/month" => "entries#calendar", as: :calendar

  scope module: :application do
    get :version
  end

  scope module: :internal do
    get :backup
    get :backup_failed, path: "backup/failed"
    get :backup_succeeded, path: "backup/succeeded"
    get :generate_backup, to: redirect("backup")
    post :generate_backup
  end
end

app/views/templates/_form.html.haml
= form_with model: template, local: true do |form|
  = render "forms/horizontal/text_field", form: form, object: template, key: :name

  .form-group.row
    %label.col-md-2.col-form-label Items
    .col-md-10
      = link_to "Add Item", add_item_templates_path, method: :post, remote: true, class: "btn btn-sm btn-light", style: "margin-top: 6px"
  #items{ data: { object: "sortable" } }
    = hidden_field_tag "template[item_ids][]", nil
    - @template.template_items.each do |template_item|
      = render "template_items/form", template_item: template_item

  = render "forms/horizontal/submit", form: form, object: template

app/views/templates/add_item.js.erb
$("#items").append("<%=j render 'template_items/form', template_item: nil %>");

app/views/templates/edit.html.haml
- @title = "Edit Template - #{@template.name_was}"

- content_for :header, @template.name_was
= render "internal/tabs"
- content_for :breadcrumbs do
  %ol
    %li= link_to "templates", templates_path
    %li= link_to @template.name_was.to_s.downcase, @template
    %li.breadcrumb-muted edit
- content_for :sidebar, render("internal/sidebar_setup")

.dashboard-container= render "templates/form", template: @template

app/views/templates/index.html.haml
- @title = "Templates"

- content_for :header do
  .float-right
    = link_to plus_or("New Template"), new_template_path, class: "btn btn-primary btn-shadow"
  = @title
  = render "search/toggle"
= render "internal/tabs"
- content_for :breadcrumbs do
  = render "layouts/per_page_breadcrumbs", per_page: 40, object_count: @templates.total_count
  %ol
    %li.breadcrumb-muted templates
- content_for :sidebar, render("internal/sidebar_setup")

= render "search/simple", url: templates_path

- if @templates.present?
  .dashboard-container.dashboard-table
    %table.table.table-striped.table-borderless.table-hover.table-sticky
      %col
      %col{ width: "1px" }
      %thead
        %tr
          %th Name
          %th.text-center Actions

      %tbody
        - @templates.each do |template|
          %tr
            %td= link_to template.name, template
            %td.text-center
              = render "layouts/edit_delete_dropdown", edit_url: edit_template_path(template), delete_url: template, delete_confirmation: "Delete #{template.name}?"

  .center-horizontally= paginate @templates, theme: 'bootstrap'
- else
  .jumbotron.jumbotron-custom-text
    = icon("far", "clone", class: "mr-1")
    No templates found.
    = link_to "Start over", templates_path if params[:search].present?

app/views/templates/launch_template.js.erb
showEntryContents();
$('#new-entry-dialog').modal('hide');
$('#new_entry')[0].reset();
$('.has-error').removeClass('has-error');

app/views/templates/new.html.haml
- @title = "New Template"

- content_for :header, @title
= render "internal/tabs"
- content_for :breadcrumbs do
  %ol
    %li= link_to "templates", templates_path
    %li.breadcrumb-muted new
- content_for :sidebar, render("internal/sidebar_setup")

.dashboard-container= render "templates/form", template: @template

app/views/templates/show.html.haml
- @title = @template.name

- content_for :header do
  .float-right
    = render "layouts/edit_delete_dropdown", edit_url: edit_template_path(@template), delete_url: @template, delete_confirmation: "Delete #{@template.name}?"
  = @title
= render "internal/tabs"
- content_for :breadcrumbs do
  %ol
    %li= link_to "templates", templates_path
    %li.breadcrumb-muted= @template.name.to_s.downcase
- content_for :sidebar, render("internal/sidebar_setup")

- if @template.template_items.present?
  .dashboard-container.dashboard-table
    %table.table.table-striped.table-borderless.table-hover.table-sticky
      %thead
        %tr
          %th Name
          %th Amount
          %th Charge Type
          %th Description
      - @template.template_items.each do |template_item|
        %tr
          %td= template_item.name
          %td= template_item.amount.to_currency
          %td= template_item.charge_type.name
          %td= simple_format template_item.description
- else
  .jumbotron.jumbotron-custom-text
    = icon("far", "clone", class: "mr-1")
    Template has no items.