config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "entries#calendar"

  resources :accounts do
    get :search, on: :collection
  end

  resources :charge_types, path: "charge-types" do
    get :search, on: :collection
  end

  resources :entries do
    member do
      post :mark_charged
      get :copy
      post :move
    end
    collection do
      get :calendar
      get :overview
      post :earning_spending_graph
      get :statistics
      post :statistics_graph, path: "statistics"
      get :autocomplete
      get :averages
      get :current_balance, path: "current-balance"
    end
  end

  resources :templates do
    collection do
      post :add_item
      post :launch_template
    end
  end

  devise_for :users,
             controllers: {
               passwords: "passwords",
               registrations: "registrations",
               sessions: "sessions",
               unlocks: "unlocks"
             },
             path_names: { sign_up: "join", sign_in: "login" },
             path: ""

  get "/about" => "application#about", as: :about
  get "/month" => "entries#calendar", as: :calendar

  scope module: :application do
    get :version
  end

  scope module: :internal do
    get :backup
    get :backup_failed, path: "backup/failed"
    get :backup_succeeded, path: "backup/succeeded"
    get :generate_backup, to: redirect("backup")
    post :generate_backup
  end
end

app/models/account.rb
# frozen_string_literal: true

# Stores the total value of a single account. Can have multiple charge types
# that can count towards spending or be transfers.
class Account < ApplicationRecord
  # Triggers
  after_create_commit :create_transfer_charge_type

  # Constants
  CATEGORIES = [%w(Savings savings), %w(Investments investments)]

  # Concerns
  include Searchable, Deletable, Squishable

  squish :name

  # Model Validation
  validates :name, presence: true
  validates :category, inclusion: { in: CATEGORIES.collect(&:second) }

  # Model Relationships
  belongs_to :user
  has_many :charge_types, -> { current.order(:name) }

  # Account Methods

  def total_spent
    @total_spent ||= begin
      charge_types.collect(&:total_spent).sum
    end
  end

  # type: :amount, :charged_amount
  def balance(type)
    charge_types.collect { |c| c.contribution(type) }.sum
  end

  def spent_in_time_period(start_date, end_date)
    @spent_in_time_period ||= begin
      charge_types.collect { |item| item.spent_in_time_period(start_date, end_date) }.sum
    end
  end

  def average_spent_over_time_period(start_date, end_date)
    @average_spent_over_time_period ||= begin
      spent_in_time_period(start_date, end_date) / (end_date - start_date + 1.0)
    end
  end

  def category_name
    Account.category_name(category)
  end

  def self.category_name(category)
    CATEGORIES.find { |_name, value| value == category }.first
  rescue
    'Uncategorized'
  end

  def create_transfer_charge_type
    charge_types.create(name: 'Transfer', counts_towards_spending: false)
  end
end

app/controllers/accounts_controller.rb
# frozen_string_literal: true

# Allows users to modify and edit existing accounts.
class AccountsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_account_or_redirect, only: [:show, :edit, :update, :destroy]

  layout "layouts/full_page_sidebar"

  # GET /accounts
  def index
    scope = current_user.accounts
    scope = scope_includes(scope)
    scope = scope_filter(scope)
    @accounts = scope_order(scope).page(params[:page]).per(40)
  end

  # # GET /accounts/1
  # def show
  # end

  # GET /accounts/new
  def new
    @account = current_user.accounts.new
  end

  # # GET /accounts/1/edit
  # def edit
  # end

  # POST /accounts
  def create
    @account = current_user.accounts.new(account_params)
    if @account.save
      redirect_to @account, notice: 'Account was successfully created.'
    else
      render :new
    end
  end

  # PATCH /accounts/1
  def update
    if @account.update(account_params)
      redirect_to @account, notice: 'Account was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /accounts/1
  def destroy
    @account.destroy
    redirect_to accounts_path
  end

  private

  def find_account_or_redirect
    @account = current_user.accounts.find_by(id: params[:id])
    redirect_without_account
  end

  def redirect_without_account
    empty_response_or_root_path(accounts_path) unless @account
  end

  def account_params
    params.require(:account).permit(:name, :category, :archived)
  end

  def scope_includes(scope)
    scope.includes(:charge_types)
  end

  def scope_filter(scope)
    scope.search(params[:search])
  end

  def scope_order(scope)
    @order = scrub_order(
      Account, params[:order],
      'accounts.archived, accounts.category desc, accounts.name'
    )
    scope.order(@order)
  end
end

app/views/accounts/_charge_types.html.haml
- if account.charge_types.present?
  %ul.list-unstyled
    - account.charge_types.each do |charge_type|
      %li= link_to charge_type.name, charge_type
- else
  .text-muted No charge types.

app/views/accounts/_form.html.haml
= form_with model: account, local: true do |form|
  = render "forms/horizontal/text_field", form: form, object: account, key: :name
  = render "forms/horizontal/check_box", form: form, object: account, key: :archived, help_text: "Archived accounts do not display in current balance."
  = render "forms/horizontal/select", form: form, object: account, key: :category, options: Account::CATEGORIES
  = render "forms/horizontal/submit", form: form, object: account

app/views/accounts/_month_spending.html.haml
%h2
  Spending This Month

%table.table.table-striped.table-borderless
  %thead
    %tr
      %th Account
      %th.text-right Spending
      %th.text-right Daily Average
  %tbody
    - current_user.accounts.each do |account|
      - unless account.spent_in_time_period(@start_month, @end_month).zero?
        %tr
          %td= link_to account.name, account
          %td.text-right= account.spent_in_time_period(@start_month, @end_month).to_currency
          %td.text-right= account.average_spent_over_time_period(@start_month, @end_month).to_currency
  %tfoot
    %tr
      %th Total
      %th.text-right= current_user.spent_in_time_period(@start_month, @end_month).to_currency
      %th.text-right= current_user.average_spent_over_time_period(@start_month, @end_month).to_currency

app/views/accounts/_search.html.erb
<table class="search"><tr><th>Account Name</th></tr>
<% @accounts.each do |account| %>
	<tr>
		<td><%= link_to account.name, account %></td>
	</tr>
<% end %>
</table>
<%= will_paginate @accounts, :class => 'pagination ajax' %>

app/views/accounts/edit.html.haml
- @title = "Edit Account - #{@account.name_was}"

- content_for :header, @account.name_was
= render "internal/tabs"
- content_for :breadcrumbs do
  %ol
    %li= link_to "accounts", accounts_path
    %li= link_to @account.name_was.to_s.downcase, @account
    %li.breadcrumb-muted edit
- content_for :sidebar, render("internal/sidebar_setup")

.dashboard-container= render "accounts/form", account: @account

app/views/accounts/index.html.haml
- @title = "Accounts"

- content_for :header do
  .float-right
    = link_to plus_or("New Account"), new_account_path, class: "btn btn-primary btn-shadow"
  = @title
  = render "search/toggle"
= render "internal/tabs"
- content_for :breadcrumbs do
  = render "layouts/per_page_breadcrumbs", per_page: 40, object_count: @accounts.total_count
  %ol
    %li.breadcrumb-muted accounts
- content_for :sidebar, render("internal/sidebar_setup")

= render "search/simple", url: accounts_path

- if @accounts.present?
  .dashboard-container.dashboard-table
    %table.table.table-striped.table-borderless.table-hover.table-sticky
      %thead
        %tr
          %th Account Name
          %th Category
          %th Charge Types
          %th.text-center Archived
      %tbody
        - @accounts.each do |account|
          %tr
            %td= link_to account.name, account
            %td= account.category_name
            %td= account.charge_types.collect { |charge_type| link_to charge_type.name, charge_type }.join(", ").html_safe
            %td.text-center= simple_check account.archived?

  .center-horizontally= paginate @accounts, theme: "bootstrap"
- else
  .jumbotron.jumbotron-custom-text
    = icon("far", "clone", class: "mr-1")
    No accounts found.
    = link_to "Start over", accounts_path if params[:search].present?

app/views/accounts/index.js.erb
$("#accounts").html("<%=j render 'accounts' %>");

app/views/accounts/new.html.haml
- @title = "New Account"

- content_for :header, @title
= render "internal/tabs"
- content_for :breadcrumbs do
  %ol
    %li= link_to "accounts", accounts_path
    %li.breadcrumb-muted new
- content_for :sidebar, render("internal/sidebar_setup")

.dashboard-container= render "accounts/form", account: @account

app/views/accounts/show.html.haml
- @title = @account.name

- content_for :header do
  .float-right
    = render "layouts/edit_delete_dropdown", edit_url: edit_account_path(@account), delete_url: @account, delete_confirmation: "Delete #{@account.name}?"
  = @title
= render "internal/tabs"
- content_for :breadcrumbs do
  %ol
    %li= link_to "accounts", accounts_path
    %li.breadcrumb-muted= @account.name.to_s.downcase
- content_for :sidebar, render("internal/sidebar_setup")

.dashboard-container
  = render "forms/horizontal/show/text", object: @account, key: :category_name
  = render "forms/horizontal/show/generic", title: "Current balance", content: @account.balance(:amount).to_currency
  = render "forms/horizontal/show/generic", title: "Total spent", content: @account.total_spent.to_currency
  = render "forms/horizontal/show/generic", title: "Charge types", content: render("accounts/charge_types", account: @account)